ISFinalProject/Models/Barangay.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;

namespace ISFinalProject.Models
{
	public class Barangay
	{
		public int Id { get; set; }
		//civilian info
		[Required]
		public string FirstName { get; set; }
		[Required]
		public string LastName { get; set; }
		public int Age { get; set; }
		[Required]
		public string Gender { get; set; }
		[Required]
		public string CivilStatus { get; set; }
		public int HouseNo { get; set; }
		[Required]
		public string Occupation { get; set; }
		public double annualIncome { get; set; }

		//contacts
		[Required]
		public string ContactNo { get; set; }
		public string Gmail { get; set; }
	}
}

ISFinalProject/Models/ErrorViewModel.cs
namespace ISFinalProject.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

ISFinalProject/Controllers/BrgyController.cs
using ISFinalProject.Data;
using ISFinalProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ISFinalProject.Controllers
{
	public class BrgyController : Controller
	{
		private readonly ApplicationDbContext _db;
        public BrgyController(ApplicationDbContext db)
        {
			_db = db;
        }

        public async Task<IActionResult> Index()
		{
			List<Barangay?> brgyList = await _db.Barangays.ToListAsync();
			return View(brgyList);
		}

		[HttpGet]
		public IActionResult Create(int? id)
		{
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,Age,Gender,CivilStatus,HouseNo,Occupation,annualIncome,ContactNo,Gmail")] Barangay brgy)
		{
			if(ModelState.IsValid)
			{
				await _db.Barangays.AddAsync(brgy);
				await _db.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}
			return View(brgy);
		}

		public IActionResult Edit(int? id)
		{
			if(id == null || id == 0)
			{
				return NotFound();
			}

			Barangay? brgy = _db.Barangays.FirstOrDefault(u => u.Id == id);

			if(brgy == null)
			{
				return NotFound();
			}

			return View(brgy);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int? id, [Bind("Id,FirstName,LastName,Age,Gender,CivilStatus,HouseNo,Occupation,annualIncome,ContactNo,Gmail")] Barangay brgy)
		{
			if (id != brgy.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				_db.Barangays.Update(brgy);
				await _db.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}
			return View(brgy);
		}

		public IActionResult Delete(int? id)
		{
			if(id == null || id == 0)
			{
				return NotFound();
			}

			Barangay? brgy = _db.Barangays.FirstOrDefault(u => u.Id == id);

			if(brgy == null)
			{
				return NotFound();
			}

			return View(brgy);
		}

		[HttpPost, ActionName("Delete")]
		public async Task<IActionResult> DeletePost(int? id)
		{
			if (_db.Barangays == null)
			{
				return Problem("Entity set 'ApplicationDbContext.Barangays'  is null.");
			}
			Barangay? brgy = await _db.Barangays.FirstOrDefaultAsync(u => u.Id == id);
			if (brgy != null)
			{
				_db.Barangays.Remove(brgy);
			}

			await _db.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}
	}
}

ISFinalProject/Controllers/HomeController.cs
using ISFinalProject.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ISFinalProject.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

ISFinalProject/Views/Brgy/Create.cshtml
@model ISFinalProject.Models.Barangay;

<form method="post" asp-action="Create" class="form">
    <p class="title">Citizen Information </p>
    <p class="message">All civil information that you provided are private. </p>
    <div class="flex">
        <label>
            <input type="text" class="input" asp-for="FirstName">
            <span>Firstname</span>
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </label>

        <label>
            <input type="text" class="input" asp-for="LastName">
            <span>Lastname</span>
            <span asp-validation-for="LastName" class="text-danger"></span>
        </label>
    </div>

    <label>
        <span>Age</span>
        <input type="number" class="input" asp-for="Age">
        <span asp-validation-for="Age" class="text-danger"></span>
    </label>

    <label>
        <input type="text" class="input" asp-for="Gender">
        <span>Gender</span>
        <span asp-validation-for="Gender" class="text-danger"></span>
    </label>

    <label>
        <input type="text" class="input" asp-for="CivilStatus">
        <span>Civil Status</span>
        <span asp-validation-for="CivilStatus" class="text-danger"></span>
    </label>

    <label>
        <span>House No.</span>
        <input type="number" class="input" asp-for="HouseNo">
        <span asp-validation-for="HouseNo" class="text-danger"></span>
    </label>

    <label>
        <input type="text" class="input" asp-for="Occupation">
        <span>Occupation</span>
        <span asp-validation-for="Occupation" class="text-danger"></span>
    </label>

    <label>
        <span>Annual Income</span>
        <input type="number" class="input" asp-for="annualIncome">
        <span asp-validation-for="annualIncome" class="text-danger"></span>
    </label>

    <p class="title">Citizen Contacts </p>
    <p class="message">All citizen contacts that you provided are private. </p>

    <label>
        <input type="text" class="input" asp-for="ContactNo">
        <span>Contact No.</span>
        <span asp-validation-for="ContactNo" class="text-danger"></span>
    </label>

    <label>
        <input type="email" class="input" asp-for="Gmail" placeholder="bsinfo2b@gmail.com">
        <span>Gmail</span>
        <span asp-validation-for="Gmail" class="text-danger"></span>
    </label>

    <button type="submit" class="submit"> <i class="bi bi-plus-circle"></i> Submit</button>
</form>

ISFinalProject/Views/Brgy/Delete.cshtml
@model ISFinalProject.Models.Barangay;

<form method="post" asp-action="Delete" class="form">
    <input asp-for="Id" hidden />
    <p class="title">Citizen Information </p>
    <p class="message">All civil information that you provided are private. </p>
    <div class="flex">
        <label>
            <input type="text" class="input" asp-for="FirstName" disabled>
            <span>Firstname</span>
        </label>

        <label>
            <input type="text" class="input" asp-for="LastName" disabled>
            <span>Lastname</span>           
        </label>
    </div>

    <label>
        <span>Age</span>
        <input type="number" class="input" asp-for="Age" disabled>
    </label>

    <label>
        <input type="text" class="input" asp-for="Gender" disabled>
        <span>Gender</span>
    </label>

    <label>
        <input type="text" class="input" asp-for="CivilStatus" disabled>
        <span>Civil Status</span>
    </label>

    <label>
        <span>House No.</span>
        <input type="number" class="input" asp-for="HouseNo" disabled>
    </label>

    <label>
        <input type="text" class="input" asp-for="Occupation" disabled>
        <span>Occupation</span>
    </label>

    <label>
        <span>Annual Income</span>
        <input type="number" class="input" asp-for="annualIncome" disabled>
    </label>

    <p class="title">Citizen Contacts </p>
    <p class="message">All citizen contacts that you provided are private. </p>

    <label>
        <input type="text" class="input" asp-for="ContactNo" disabled>
        <span>Contact No.</span>
    </label>

    <label>
        <input type="email" class="input" asp-for="Gmail" placeholder="bsinfo2b@gmail.com" disabled>
        <span>Gmail</span>
    </label>

    <button type="submit" class="submit"> <i class="bi bi-trash-fill"></i> Delete</button>
</form>

ISFinalProject/Views/Brgy/Edit.cshtml
@model ISFinalProject.Models.Barangay;

<form method="post" asp-action="Edit" class="form">
    <p class="title">Citizen Information </p>
    <p class="message">All civil information that you provided are private. </p>
    <div class="flex">
        <label>
            <input type="text" class="input" asp-for="FirstName">
            <span>Firstname</span>
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </label>

        <label>
            <input type="text" class="input" asp-for="LastName">
            <span>Lastname</span>
            <span asp-validation-for="LastName" class="text-danger"></span>
        </label>
    </div>

    <label>
        <span>Age</span>
        <input type="number" class="input" asp-for="Age">
        <span asp-validation-for="Age" class="text-danger"></span>
    </label>

    <label>
        <input type="text" class="input" asp-for="Gender">
        <span>Gender</span>
        <span asp-validation-for="Gender" class="text-danger"></span>
    </label>

    <label>
        <input type="text" class="input" asp-for="CivilStatus">
        <span>Civil Status</span>
        <span asp-validation-for="CivilStatus" class="text-danger"></span>
    </label>

    <label>
        <span>House No.</span>
        <input type="number" class="input" asp-for="HouseNo">
        <span asp-validation-for="HouseNo" class="text-danger"></span>
    </label>

    <label>
        <input type="text" class="input" asp-for="Occupation">
        <span>Occupation</span>
        <span asp-validation-for="Occupation" class="text-danger"></span>
    </label>

    <label>
        <span>Annual Income</span>
        <input type="number" class="input" asp-for="annualIncome">
        <span asp-validation-for="annualIncome" class="text-danger"></span>
    </label>

    <p class="title">Citizen Contacts </p>
    <p class="message">All citizen contacts that you provided are private. </p>

    <label>
        <input type="text" class="input" asp-for="ContactNo">
        <span>Contact No.</span>
        <span asp-validation-for="ContactNo" class="text-danger"></span>
    </label>

    <label>
        <input type="email" class="input" asp-for="Gmail" placeholder="bsinfo2b@gmail.com">
        <span>Gmail</span>
        <span asp-validation-for="Gmail" class="text-danger"></span>
    </label>

    <button type="submit" class="submit"> <i class="bi bi-pencil-square"></i> Update</button>
</form>

ISFinalProject/Views/Brgy/Index.cshtml
@model IEnumerable<ISFinalProject.Models.Barangay>;

<div class="card shadow border-0 mt-4">
	<div class="card-header bg-primary bg-gradient ml-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h2 class="text-white py-2">Barangay Citizens List</h2>
			</div>
		</div>
	</div>

	<div class="card-body p-4">
		<div class="row pb-3">
			<div class="col-6"></div>
			<div class="col-6 text-end">
				<a asp-controller="Brgy" asp-action="Create" class="btn btn-primary">
					<i class="bi bi-plus-circle"></i> &nbsp; ADD INFORMATION
				</a>
			</div>
		</div>
		<table class="table table-border table-striped">
			<thead>
				<tr>
					<th>
						ID
					</th>
					<th>
						First Name
					</th>
					<th>
						Last Name
					</th>
					<th>
						Age
					</th>
					<th>
						Gender
					</th>
					<th>
						Civil Status
					</th>
					<th>
						House No.
					</th>
					<th>
						Occupation
					</th>
					<th>
						Annual Income
					</th>
					<th>
						Contact No.
					</th>
					<th>
						Gmail
					</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				@foreach (var obj in Model)
				{
					<tr>
						<td>@obj.Id</td>
						<td>@obj.FirstName</td>
						<td>@obj.LastName</td>
						<td>@obj.Age</td>
						<td>@obj.Gender</td>
						<td>@obj.CivilStatus</td>
						<td>@obj.HouseNo</td>
						<td>@obj.Occupation</td>
						<td>@obj.annualIncome</td>
						<td>@obj.ContactNo</td>
						<td>@obj.Gmail</td>
						<td>
							<div class="w-75 btn-group" role="group">
								<a asp-controller="Brgy" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-primary mx-2">
									<i class="bi bi-pencil-square"></i> Edit
								</a>

								<a asp-controller="Brgy" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger mx-2">
									<i class="bi bi-trash-fill"></i> Delete
								</a>
							</div>
						</td>
					</tr>
				}
			</tbody>
		</table>
	</div>
</div>

ISFinalProject/Views/Home/Index.cshtml
<H1 CLASS="BIS"> BARANGAY INFORMATION SYSTEM </H1>
<H6 CLASS="FPII"> FINAL PROJECT IN ITEC205 </H6>

<DIV class="slide-up1">
	<BR><BR><BR><P>CLARK DAVID CATLE</P>
</DIV>

<DIV class="slide-up2">
	<BR><BR><BR><P>IAN THEODORE MALOLES</P>
</DIV>

<DIV class="slide-up3">
	<BR><BR><BR><P>JOHN CARLO MISA</P>
</DIV>

<DIV class="slide-up4">
	<BR><BR><BR><P>LAWRENCE BAUSTISTA</P>
</DIV>

<DIV class="slide-up5">
	<BR><BR><BR><P>PRINCE DARRELL MASA</P>
</DIV>

ISFinalProject/Views/Shared/_Layout.cshtml
@* <!DOCTYPE html>
<html lang="en"> *@
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ISFinalProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ISFinalProject.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
</head>


<HEADER>	
	<DIV CLASS="LOGO">
		<A asp-area="" asp-controller="Home" asp-action="Index"> <img src="@Url.Content("~/images/logo.png")" alt="logo" width="50PX" height="50PX" /> </A>
	</DIV>

	@* <H1 CLASS="BIS"> BARANGAY INFORMATION SYSTEM </H1>
	<H6 CLASS="FPII"> FINAL PROJECT IN ITEC205 </H6> *@
		
	<DIV class="NAVIGATORS">
		<UL class="MAIN-NAV">
			<LI CLASS="HOME"> <A asp-area="" asp-controller="Home" asp-action="Index">HOME</A></LI>
			<LI CLASS="CIMFA"><A asp-area="" asp-controller="Brgy" asp-action="Index">MANAGE</A></LI>
			<LI CLASS="ACT"><A asp-area="" asp-controller="Home" asp-action="Privacy">PRIVACY</A></LI>
		</UL>
	</DIV>			
</HEADER>

<body>
	<div CLASS="LSPU"><img src="@Url.Content("~/images/LSPU.png")" alt="lspuLogo"/> </div>

	<div CLASS="CCS"><img src="@Url.Content("~/images/CCS.png")" alt="ccsLogo" WIDTH="100PX"/> </div>
		
	@* <DIV class="slide-up1">
		<BR><BR><BR><P>CLARK DAVID CATLE</P>
	</DIV>
		
	<DIV class="slide-up2">
		<BR><BR><BR><P>IAN THEODORE MALOLES</P>
	</DIV>
		
	<DIV class="slide-up3">
		<BR><BR><BR><P>JOHN CARLO MISA</P>
	</DIV>
		
	<DIV class="slide-up4">
		<BR><BR><BR><P>LAWRENCE BAUSTISTA</P>
	</DIV>
		
	<DIV class="slide-up5">
		<BR><BR><BR><P>PRINCE DARRELL MASA</P>
	</DIV> *@

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>